weights: my_yolov5
cfg: /mnt/data1/ghh/my_yolov5/models/yolov5s.yaml
data: my_yolov5/data/paowu.yaml
hyp: my_yolov5/data/hyps/hyp.scratch-low.yaml
epochs: 300
batch_size: 8
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: 0,1,2,3
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: my_yolov5/runs/train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: my_yolov5/runs/train/exp5
